package BOM::Database::AutoGenerated::Rose::TouchBet::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::TouchBet;

sub object_class { 'BOM::Database::AutoGenerated::Rose::TouchBet' }

__PACKAGE__->make_manager_methods('touch_bet');

1;

