package BOM::Database::AutoGenerated::Rose::WesternUnion::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::WesternUnion;

sub object_class { 'BOM::Database::AutoGenerated::Rose::WesternUnion' }

__PACKAGE__->make_manager_methods('western_union');

1;

