package BOM::Database::AutoGenerated::Rose::Audit::RunBet::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Audit::RunBet;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Audit::RunBet' }

__PACKAGE__->make_manager_methods('run_bet');

1;

