package BOM::Database::AutoGenerated::Rose::Client::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Client;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Client' }

__PACKAGE__->make_manager_methods('client');

1;

