package BOM::Database::AutoGenerated::Rose::Audit::PaymentFee::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Audit::PaymentFee;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Audit::PaymentFee' }

__PACKAGE__->make_manager_methods('payment_fee');

1;

