package BOM::Database::AutoGenerated::Rose::MarketGlobalPotentialLoss::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::MarketGlobalPotentialLoss;

sub object_class { 'BOM::Database::AutoGenerated::Rose::MarketGlobalPotentialLoss' }

__PACKAGE__->make_manager_methods('market_global_potential_loss');

1;

