package BOM::Database::AutoGenerated::Rose::Auth::AccessToken;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'access_token',
    schema   => 'auth',

    columns => [
        token          => { type => 'text', not_null => 1 },
        display_name   => { type => 'text', not_null => 1 },
        client_loginid => { type => 'text', not_null => 1 },
        creation_time  => { type => 'timestamp', default => 'now()', not_null => 1 },
        last_used      => { type => 'timestamp' },
        scopes         => { type => 'array' },
        valid_for_ip   => { type => 'varchar', length => 64 },
    ],

    primary_key_columns => [ 'token' ],

    allow_inline_column_values => 1,
);

1;

