package BOM::Database::AutoGenerated::Rose::Runs::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Runs;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Runs' }

__PACKAGE__->make_manager_methods('runs');

1;

