package BOM::Database::AutoGenerated::Rose::CryptocurrencyHistory::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::CryptocurrencyHistory;

sub object_class { 'BOM::Database::AutoGenerated::Rose::CryptocurrencyHistory' }

__PACKAGE__->make_manager_methods('cryptocurrency_history');

1;

