package BOM::Database::AutoGenerated::Rose::PaymentType::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::PaymentType;

sub object_class { 'BOM::Database::AutoGenerated::Rose::PaymentType' }

__PACKAGE__->make_manager_methods('payment_type');

1;

