package BOM::Database::AutoGenerated::Rose::Accumulator;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table  => 'accumulator',
    schema => 'bet',

    columns => [
        financial_market_bet_id => {
            type     => 'bigint',
            not_null => 1
        },
        take_profit_order_date   => {type => 'timestamp'},
        take_profit_order_amount => {type => 'numeric'},
        growth_rate              => {type => 'numeric'},
        ask_spread               => {type => 'numeric'},
        bid_spread               => {type => 'numeric'},
    ],

    primary_key_columns => ['financial_market_bet_id'],
);

1;

