package BOM::Database::AutoGenerated::Rose::CallputSpread;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'callput_spread',
    schema   => 'bet',

    columns => [
        financial_market_bet_id => { type => 'bigint', not_null => 1 },
        relative_high_barrier   => { type => 'varchar', length => 20 },
        absolute_high_barrier   => { type => 'numeric' },
        relative_low_barrier    => { type => 'varchar', length => 20 },
        absolute_low_barrier    => { type => 'numeric' },
    ],

    primary_key_columns => [ 'financial_market_bet_id' ],
);

1;

