package BOM::Database::AutoGenerated::Rose::ClientStatusCode;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'client_status_codes',
    schema   => 'betonmarkets',

    columns => [
        status_code         => { type => 'varchar', length => 50, not_null => 1 },
        status_description  => { type => 'varchar', length => 100 },
        is_hidden           => { type => 'boolean', default => 'false', not_null => 1, remarks => 'Indicates a status_code which is not exposed or returned through the public API' },
        is_login_disallowed => { type => 'boolean', default => 'false', not_null => 1, remarks => 'Indicates a status_code which prevents the user from accessing this client account' },
    ],

    primary_key_columns => [ 'status_code' ],

    relationships => [
        clients => {
            map_class => 'BOM::Database::AutoGenerated::Rose::ClientStatus',
            map_from  => 'client_status_code',
            map_to    => 'client',
            type      => 'many to many',
        },
    ],
);

1;

