package BOM::Database::AutoGenerated::Rose::CoinauctionBet;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'coinauction_bet',
    schema   => 'bet',

    columns => [
        financial_market_bet_id => { type => 'bigint', not_null => 1 },
        coin_address            => { type => 'text', not_null => 1 },
        token_type              => { type => 'text', not_null => 1 },
        number_of_tokens        => { type => 'numeric', not_null => 1 },
        auction_date_start      => { type => 'timestamp' },
        per_token_bid_price     => { type => 'numeric', not_null => 1}
    ],

    primary_key_columns => [ 'financial_market_bet_id' ],
);

1;

