package BOM::Database::AutoGenerated::Rose::Cryptocurrency;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'cryptocurrency',
    schema   => 'payment',

    columns => [
        address                => { type => 'varchar', length => 100, not_null => 1 },
        loginid                => { type => 'varchar', length => 12 },
        account_id             => { type => 'bigint', not_null => 1 },
        amount                 => { type => 'numeric', default => '0', not_null => 1, precision => 8, scale => 16 },
        currency_code          => { type => 'varchar', length => 3, not_null => 1 },
        transaction_type       => { type => 'enum', check_in => [ 'deposit', 'withdrawal' ], db_type => 'payment.payment_txn_type', not_null => 1 },
        status                 => { type => 'varchar', length => 20, not_null => 1 },
        creation_date          => { type => 'timestamp', default => 'now()' },
        deposit_request_date   => { type => 'timestamp' },
        deposit_confirmed_date => { type => 'timestamp' },
        withdrawal_sent_date   => { type => 'timestamp' },
        payment_id             => { type => 'bigint' },
        ip_address             => { type => 'scalar' },
        remark                 => { type => 'text' },
    ],

    primary_key_columns => [ 'address', 'currency_code' ],

    allow_inline_column_values => 1,

    foreign_keys => [
        payment => {
            class       => 'BOM::Database::AutoGenerated::Rose::Payment',
            key_columns => { payment_id => 'id' },
        },
    ],
);

1;

