package BOM::Database::AutoGenerated::Rose::LookbackOption;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'lookback_option',
    schema   => 'bet',

    columns => [
        financial_market_bet_id => { type => 'bigint', not_null => 1 },
        relative_barrier        => { type => 'varchar', length => 20 },
        absolute_barrier        => { type => 'numeric' },
    ],

    primary_key_columns => [ 'financial_market_bet_id' ],
);

1;

