package BOM::Database::AutoGenerated::Rose::PaymentAgentTransfer;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table  => 'payment_agent_transfer',
    schema => 'payment',

    columns => [
        payment_id => {
            type     => 'bigint',
            not_null => 1
        },
        corresponding_payment_id => {type => 'bigint'},
    ],

    primary_key_columns => ['payment_id'],

    foreign_keys => [
        corresponding_payment => {
            class       => 'BOM::Database::AutoGenerated::Rose::Payment',
            key_columns => {corresponding_payment_id => 'id'},
        },

        payment => {
            class       => 'BOM::Database::AutoGenerated::Rose::Payment',
            key_columns => {payment_id => 'id'},
            rel_type    => 'one to one',
        },
    ],
);

1;

