package BOM::Database::AutoGenerated::Rose::SanctionsCheck;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'sanctions_check',
    schema   => 'betonmarkets',

    columns => [
        client_loginid => { type => 'varchar', length => 12, not_null => 1 },
        tstmp          => { type => 'timestamp', default => 'now()', not_null => 1 },
        type           => { type => 'varchar', default => 'R', length => 1, not_null => 1 },
        result         => { type => 'varchar', default => '', length => 128, not_null => 1 },
    ],

    primary_key_columns => [ 'client_loginid' ],

    allow_inline_column_values => 1,

    foreign_keys => [
        client => {
            class       => 'BOM::Database::AutoGenerated::Rose::Client',
            key_columns => { client_loginid => 'loginid' },
            rel_type    => 'one to one',
        },
    ],
);

1;

