package BOM::Database::AutoGenerated::Rose::Audit::Affiliate::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Audit::Affiliate;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Audit::Affiliate' }

__PACKAGE__->make_manager_methods('affiliate');

1;

