#!/bin/bash

# cleanbom -- update bom repo's and manage bom services suitable for a dev-box.

usage="usage: cleanbom [--nf] [--gs] [SERVICE_ACTION]"
#    eg: cleanbom restart

# --nf : do not fetch.
# --gs : run git-status.  implies --nf.
# service-action : defaults to 'status'.  It will apply to all devbox services.

fetch=1
service_action=status
git_status=

while [ "$1" ]; do
    case "$1" in
                             --nf) fetch=;;
                             --gs) fetch=; git_status=1;;
        stop|start|restart|status) service_action=$1;;
                                *) echo $usage; exit 1;;
    esac
    shift
done

function fetch_repo() {

    branch=$1
    repo=$2
    echo '_______________________________________________________________'
    echo "Repo $repo, branch $branch: "

    cd $repo || return 1

    if git status >/dev/null 2>&1; then
        :
    else
        echo $repo is not a repo
        return 1
    fi

    current_branch=$(git branch | awk '/^\*/ {print $2}')
    if [ ! "$fetch" ]; then
        echo "Current branch is $current_branch"
        if [ $git_status ]; then
            git status
        fi
        return 0
    fi

    origin=$(git remote -v | awk '/fetch/ {print $2}')
    echo "Fetching $origin.."
    git fetch -p || return 1

    if [ "$current_branch" != $branch ]; then
        echo "Current branch is $current_branch, will not rebase."
        return 0
    fi

    git reset --hard @{u} || return 1
    #ctags -R 2>/dev/null

    return 0
}

fetch_repo master     /home/git/bom;                                 echo
fetch_repo master     /home/git/regentmarkets/bom-app;               echo
fetch_repo master     /home/git/regentmarkets/bom-utility;           echo
fetch_repo master     /home/git/regentmarkets/bom-feed;              echo
fetch_repo master     /home/git/regentmarkets/bom-web;               echo
fetch_repo master     /home/git/regentmarkets/bom-backoffice;        echo
fetch_repo master     /home/git/regentmarkets/bom-webapi;            echo
fetch_repo master     /home/git/regentmarkets/bom-paymentapi;        echo
fetch_repo master     /home/git/regentmarkets/cpan;                  echo
fetch_repo master     /home/git/regentmarkets/chef;                  echo
fetch_repo master     /home/git/regentmarkets/devbox;                echo
fetch_repo gh-pages   /home/git/regentmarkets/binary-static-backoffice; echo
fetch_repo production /home/git/regentmarkets/environment-manifests; echo
fetch_repo gh-pages   /home/git/binary-com/binary-static;            echo

echo
echo '_______________________________________________________________'

cd /etc/init.d
for s in binary*; do
    #echo "Service  $s.."
    service $s $service_action
    echo
done

