#!/etc/rmg/bin/perl
package main;

use strict;
use warnings;

use HTML::Entities;

use f_brokerincludeall;
use BOM::Database::AutoGenerated::Rose::Users::LoginHistory::Manager;
use BOM::Database::UserDB;
use BOM::Backoffice::PlackHelpers qw( PrintContentType );
use BOM::Backoffice::Sysinit ();
BOM::Backoffice::Sysinit::init();

PrintContentType();

my $ip         = request()->param('ip');
my $encoded_ip = encode_entities($ip);
BrokerPresentation("IP SEARCH FOR $encoded_ip");
BOM::Backoffice::Auth0::can_access(['CS']);
my $broker = request()->broker_code;

if ($ip !~ /^\d+\.\d+\.\d+\.\d+$/) {
    print "Invalid IP $encoded_ip";
    code_exit_BO();
}

Bar("Searching for Emails corresponding to $encoded_ip");
my $last_login_age = request()->param('lastndays') || 10;

# IP search from users.login_history table
my $logins = BOM::Database::AutoGenerated::Rose::Users::LoginHistory::Manager->get_login_history(
    db              => BOM::Database::UserDB::rose_db(),
    require_objects => ['binary_user'],
    query           => [
        successful   => 1,
        environment  => {like => '%IP=' . $ip . ' %'},
        history_date => {gt => DateTime->today()->subtract(days => $last_login_age)},
    ],
    sort_by => 't1.history_date DESC'
);

BOM::Backoffice::Request::template->process(
    'backoffice/ip_search.html.tt',
    {
        logins => $logins,
        days   => $last_login_age,
        ip     => $ip,
    }) || die BOM::Backoffice::Request::template->error();

code_exit_BO();
