CORETESTS=unit_test_database_datamapper \
      unit_test_database_model \
      unit_test_database_all \

ALLTESTS=syntax \
      unit_test_database_datamapper \
      unit_test_database_model \
      unit_test_database_all \

M=[ -t 1 ] && echo -e 'making \033[01;33m$@\033[00m' || echo 'making $@'
D=$(CURDIR)
P=/etc/rmg/bin/prove -rv --timer -I$D/lib -I$D -I$D/t
PROVE=p () { $M; echo '$P' "$$@"; $P "$$@"; }; p

test: $(CORETESTS)

test_all: $(ALLTESTS)

unit_test_database_datamapper:
	@$(PROVE) t/BOM/Database/DataMapper/

unit_test_database_model:
	@$(PROVE) t/BOM/Database/Model/

unit_test_database_all:
	@$(PROVE) t/BOM/Database/*.t

syntax:
	@$(PROVE) t/*.t

pod_test:
	@$(PROVE) t/*pod*.t

unit:
	/etc/rmg/bin/prove -rv --timer t/unit/

tidy:
	find . -name '*.p?.bak' -delete
	find . -not -path "./.git*" -not -path "./srp*" -name '*.p[lm]' -o -name '*.t' | grep -v 'AutoGenerated' | xargs perltidy -pro=/home/git/regentmarkets/cpan/rc/.perltidyrc --backup-and-modify-in-place -bext=tidyup
	find . -name '*.tidyup' -delete

#  The hash randomization changes since Perl 5.18 (which we revert back to the old behavior via this variable.) Refer https://perldoc.perl.org/perl5180delta.html#Hash-overhaul
orm_files:
	perl -MBOM::Test -MBOM::Test::Data::Utility::UnitTestDatabase=:init -e0
	PERL_HASH_SEED=0 PGPORT=5432 bin/rose_generation clientdb_template --all

cover:
	cover -delete
	PERL5OPT=-MBOM::Test HARNESS_PERL_SWITCHES=-MDevel::Cover DEVEL_COVER_OPTIONS=-'ignore,^t/' /etc/rmg/bin/prove --timer -rl --norc   t/BOM t/uni
	cover -report coveralls
