package BOM::Database::AutoGenerated::Rose::PaymentAgentTransfer::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::PaymentAgentTransfer;

sub object_class { 'BOM::Database::AutoGenerated::Rose::PaymentAgentTransfer' }

__PACKAGE__->make_manager_methods('payment_agent_transfer');

1;

