package BOM::Database::AutoGenerated::Rose::ContractGroup;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'contract_group',
    schema   => 'bet',

    columns => [
        bet_type       => { type => 'varchar', not_null => 1 },
        contract_group => { type => 'text', not_null => 1 },
    ],

    primary_key_columns => [ 'bet_type' ],
);

1;

