package BOM::Database::AutoGenerated::Rose::ErcCurrencyConfig;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'erc_currency_config',
    schema   => 'payment',

    columns => [
        currency_code    => { type => 'varchar', not_null => 1 },
        contract_address => { type => 'varchar', not_null => 1 },
        contract_abi     => { type => 'text', not_null => 1 },
        token_version    => { type => 'integer', not_null => 1 },
        enabled          => { type => 'boolean', not_null => 1 },
    ],

    primary_key_columns => [ 'currency_code' ],
);

1;

