package BOM::Database::AutoGenerated::Rose::Market;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'market',
    schema   => 'bet',

    columns => [
        symbol      => { type => 'text', not_null => 1 },
        market      => { type => 'text', not_null => 1 },
        submarket   => { type => 'text', not_null => 1 },
        market_type => { type => 'enum', check_in => [ 'n/a', 'financial', 'non_financial' ], db_type => 'bet.market_type' },
    ],

    primary_key_columns => [ 'symbol' ],
);

1;

