package BOM::Database::AutoGenerated::Rose::Runs;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'runs',
    schema   => 'bet',

    columns => [
        financial_market_bet_id => { type => 'bigint', not_null => 1 },
        selected_tick           => { type => 'integer' },
        relative_barrier        => { type => 'varchar', length => 20 },
    ],

    primary_key_columns => [ 'financial_market_bet_id' ],
);

1;

