package BOM::Database::AutoGenerated::Rose::SpreadBet::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::SpreadBet;

sub object_class { 'BOM::Database::AutoGenerated::Rose::SpreadBet' }

__PACKAGE__->make_manager_methods('spread_bet');

1;

