package BOM::Database::AutoGenerated::Rose::Audit::RangeBet::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Audit::RangeBet;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Audit::RangeBet' }

__PACKAGE__->make_manager_methods('range_bet');

1;

