package BOM::Database::AutoGenerated::Rose::Auth::Grant::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Auth::Grant;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Auth::Grant' }

__PACKAGE__->make_manager_methods('grants');

1;

