package BOM::Database::Model::DataCollection::QuantsBetVariables;

use Moose;
use BOM::Database::AutoGenerated::Rose::QuantsBetVariable;

extends 'BOM::Database::Model::Base';

has 'quants_bet_variables_record' => (
    is      => 'rw',
    isa     => 'Maybe[BOM::Database::AutoGenerated::Rose::QuantsBetVariable]',
    lazy    => 1,
    builder => '_build_quants_bet_variables_record',
    handles => [BOM::Database::AutoGenerated::Rose::QuantsBetVariable->meta->column_names],
);

sub _build_quants_bet_variables_record {
    my $self = shift;

    return $self->_initialize_data_access_object('BOM::Database::AutoGenerated::Rose::QuantsBetVariable',
        $self->_extract_related_attributes_for_quants_bet_variables_class_hashref());
}

sub _extract_related_attributes_for_quants_bet_variables_class_hashref {
    my $self = shift;

    my $result =
        $self->_extract_related_attributes_for_class_based_on_table_definition_hashref('BOM::Database::AutoGenerated::Rose::QuantsBetVariable');

    return $result;
}

sub save {
    my $self = shift;
    my $args = shift;

    $self->_save_orm_object({'record' => $self->quants_bet_variables_record});

    return;
}

# We need to ignore (ProhibitBuiltinHomonyms) for this specific method which
# basically overrides delete method of Rose::DB::Object and we can't help to
# just ignore perl ciritic for this line
#sub delete    ## no critic (ProhibitBuiltinHomonyms)
#{
#    my $self = shift;
#    my $args = shift;
#
#    $self->_delete_orm_object({'record' => $self->quants_bet_variables_record});
#
#    return;
#}

sub load {
    my $self = shift;
    my $args = shift;

    $self->_load_orm_object({
            'record'      => $self->quants_bet_variables_record,
            'load_params' => $args->{'load_params'}});

    return;
}

sub class_orm_record {
    my $self = shift;

    return $self->quants_bet_variables_record;
}

no Moose;
__PACKAGE__->meta->make_immutable;

1;

=pod

=head1 NAME

BOM::Database::Model::DataCollection::QuantsBetVariables

=head1 DESCRIPTION

For every bet all extra variables that are there only for inspections by poeple or repricing bet before we move all the pricing info into DB will be placed here.

Numbers like Underlying Market Price (current_spot) , gamma, theo, ....

=over 4

=item B<load>

  refer to parent

=item B<save>

  refer to parent

=item B<class_orm_record>

  refer to parent

=item B<extract_parameters_from_line>

 refer to parent

=back

=head1 VERSION

0.1

=head1 AUTHOR

RMG Company

=cut

