package BOM::Database::AutoGenerated::Rose::ClientPromoCode::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::ClientPromoCode;

sub object_class { 'BOM::Database::AutoGenerated::Rose::ClientPromoCode' }

__PACKAGE__->make_manager_methods('client_promo_code');

1;

