package BOM::Database::AutoGenerated::Rose::BetClassWithoutPayoutPrice::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::BetClassWithoutPayoutPrice;

sub object_class { 'BOM::Database::AutoGenerated::Rose::BetClassWithoutPayoutPrice' }

__PACKAGE__->make_manager_methods('bet_class_without_payout_price');

1;

