-- This will create Database, schema & Roles for feed db
CREATE DATABASE feed;

CREATE ROLE read LOGIN PASSWORD 'mRX1E3Mi00oS8LG';
CREATE ROLE write LOGIN PASSWORD	'mRX1E3Mi00oS8LG';
CREATE ROLE monitor LOGIN PASSWORD	'mRX1E3Mi00oS8LG';
CREATE ROLE replicator LOGIN REPLICATION PASSWORD	'mRX1E3Mi00oS8LG';
