package BOM::Database::AutoGenerated::Rose::BetDictionary::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::BetDictionary;

sub object_class { 'BOM::Database::AutoGenerated::Rose::BetDictionary' }

__PACKAGE__->make_manager_methods('bet_dictionary');

1;

