package BOM::Database::AutoGenerated::Rose::Users::BinaryUser;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'binary_user',
    schema   => 'users',

    columns => [
        id                 => { type => 'bigserial', not_null => 1 },
        email              => { type => 'varchar', length => 100, not_null => 1 },
        password           => { type => 'varchar', length => 100, not_null => 1 },
        email_verified     => { type => 'boolean', default => 'false', not_null => 1 },
        utm_source         => { type => 'varchar', length => 100, remarks => 'Required parameter to identify the source of your traffic such as: search engine, newsletter, or other referral' },
        utm_medium         => { type => 'varchar', length => 100, remarks => 'Required parameter to identify the medium the link was used upon such as: email, CPC, or other method of sharing' },
        utm_campaign       => { type => 'varchar', length => 100, remarks => 'Required parameter to identify a specific product promotion or strategic campaign such as a spring sale or other promotion' },
        app_id             => { type => 'bigint', remarks => 'Refers to the values found in oauth.apps.id' },
        email_consent      => { type => 'boolean' },
        gclid_url          => { type => 'text', remarks => '(Google Click Identifier) to track source' },
        has_social_signup  => { type => 'boolean' },
        secret_key         => { type => 'text' },
        is_totp_enabled    => { type => 'boolean' },
        date_first_contact => { type => 'date' },
        signup_device      => { type => 'enum', check_in => [ 'mobile', 'desktop' ], db_type => 'signup_device_type' },
    ],

    primary_key_columns => [ 'id' ],

    unique_key => [ 'email' ],

    relationships => [
        binary_user_connects => {
            class      => 'BOM::Database::AutoGenerated::Rose::Users::BinaryUserConnect',
            column_map => { id => 'binary_user_id' },
            type       => 'one to many',
        },

        failed_login => {
            class                => 'BOM::Database::AutoGenerated::Rose::Users::FailedLogin',
            column_map           => { id => 'id' },
            type                 => 'one to one',
            with_column_triggers => '0',
        },

        login_history => {
            class      => 'BOM::Database::AutoGenerated::Rose::Users::LoginHistory',
            column_map => { id => 'binary_user_id' },
            type       => 'one to many',
        },

        loginid => {
            class      => 'BOM::Database::AutoGenerated::Rose::Users::Loginid',
            column_map => { id => 'binary_user_id' },
            type       => 'one to many',
        },

        self_exclusion => {
            class      => 'BOM::Database::AutoGenerated::Rose::Users::SelfExclusion',
            column_map => { id => 'binary_user_id' },
            type       => 'one to many',
        },
    ],
);

1;

