package BOM::Database::AutoGenerated::Rose::Auth::AccessToken::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Auth::AccessToken;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Auth::AccessToken' }

__PACKAGE__->make_manager_methods('access_token');

1;

