package BOM::Database::AutoGenerated::Rose::ProductionServer::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::ProductionServer;

sub object_class { 'BOM::Database::AutoGenerated::Rose::ProductionServer' }

__PACKAGE__->make_manager_methods('production_servers');

1;

