package BOM::Database::AutoGenerated::Rose::RejectedTrade::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::RejectedTrade;

sub object_class { 'BOM::Database::AutoGenerated::Rose::RejectedTrade' }

__PACKAGE__->make_manager_methods('rejected_trades');

1;

