package BOM::Database::AutoGenerated::Rose::ClientStatus::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::ClientStatus;

sub object_class { 'BOM::Database::AutoGenerated::Rose::ClientStatus' }

__PACKAGE__->make_manager_methods('client_status');

1;

