package BOM::Database::AutoGenerated::Rose::ClientAffiliateExposure::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::ClientAffiliateExposure;

sub object_class { 'BOM::Database::AutoGenerated::Rose::ClientAffiliateExposure' }

__PACKAGE__->make_manager_methods('client_affiliate_exposure');

1;

