package BOM::Database::AutoGenerated::Rose::SymbolGlobalRealizedLossMarketDefault::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::SymbolGlobalRealizedLossMarketDefault;

sub object_class { 'BOM::Database::AutoGenerated::Rose::SymbolGlobalRealizedLossMarketDefault' }

__PACKAGE__->make_manager_methods('symbol_global_realized_loss_market_defaults');

1;

