CREATE DATABASE auth
	ENCODING='UTF8'
	LC_COLLATE='en_US.UTF-8'
	LC_CTYPE='en_US.UTF-8';

CREATE DATABASE auth_test
	ENCODING='UTF8'
	LC_COLLATE='en_US.UTF-8'
	LC_CTYPE='en_US.UTF-8';

CREATE ROLE read  LOGIN password 'mRX1E3Mi00oS8LG';
CREATE ROLE write LOGIN password 'mRX1E3Mi00oS8LG';
CREATE ROLE monitor LOGIN PASSWORD 'mRX1E3Mi00oS8LG';
CREATE ROLE replicator REPLICATION LOGIN PASSWORD 'mRX1E3Mi00oS8LG';
