#!/etc/rmg/bin/perl

use strict;
use warnings;
use Test::More (tests => 5);
use Test::Warnings;
use Test::Exception;
use BOM::Database::Model::ExchangeRate;
use BOM::Database::ClientDB;

use BOM::Test::Data::Utility::UnitTestCollectorDatabase qw(:init);

my $connection_builder;
my $exchange_rate;
my $exchange_rate_id;

lives_ok {
    $connection_builder = BOM::Database::ClientDB->new({
        broker_code => 'FOG',
    });

    $exchange_rate = BOM::Database::Model::ExchangeRate->new({
            data_object_params => {
                source_currency => 'GBP',
                target_currency => 'USD',
                date            => '2010-12-01',
                rate            => '1.6784',
            },
            db => $connection_builder->db
        });
    $exchange_rate->save();

    $exchange_rate_id = $exchange_rate->exchange_rate_record->id;

}
'expecting to load the required exchange_rate models for transfer';

isa_ok($exchange_rate->class_orm_record, 'BOM::Database::AutoGenerated::Rose::ExchangeRate');

lives_ok {

    $exchange_rate = BOM::Database::Model::ExchangeRate->new({
        data_object_params => {'id' => $exchange_rate_id},
        db                 => $connection_builder->db
    });
    $exchange_rate->load({'load_params' => {speculative => 1}});

}
'expect to load the exchange_rate even with exchange_rate_id instead of id';

cmp_ok($exchange_rate->exchange_rate_record->target_currency, 'eq', 'USD', 'Check if it load the exchange_rate properly');

