SET client_min_messages TO warning;

-- -------------------------------------------
-- User creation, Enable if needed
-- CREATE USER read WITH PASSWORD 'letmein';
-- CREATE USER write WITH PASSWORD 'letmein';
-- -------------------------------------------

GRANT CONNECT ON DATABASE feed to read;
GRANT USAGE ON SCHEMA feed to read;
GRANT SELECT ON ALL TABLES IN SCHEMA feed TO read;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA feed TO read;

GRANT CONNECT ON DATABASE feed to write;
GRANT USAGE ON SCHEMA feed to write;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER ON ALL TABLES IN SCHEMA feed TO write;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA feed TO write;

GRANT ALL PRIVILEGES ON DATABASE feed to postgres WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON SCHEMA feed to postgres WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA feed TO postgres WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA feed TO postgres WITH GRANT OPTION;

GRANT SELECT ON ALL TABLES IN SCHEMA feed TO monitor;

