package BOM::Database::AutoGenerated::Rose::Audit::PromoCode::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Audit::PromoCode;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Audit::PromoCode' }

__PACKAGE__->make_manager_methods('promo_code');

1;

