package BOM::Database::AutoGenerated::Rose::Account::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Account;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Account' }

__PACKAGE__->make_manager_methods('account');

1;

