package BOM::Database::AutoGenerated::Rose::UnderlyingSymbolCurrencyMapper::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::UnderlyingSymbolCurrencyMapper;

sub object_class { 'BOM::Database::AutoGenerated::Rose::UnderlyingSymbolCurrencyMapper' }

__PACKAGE__->make_manager_methods('underlying_symbol_currency_mapper');

1;

