package BOM::Database::AutoGenerated::Rose::CoinauctionBet::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::CoinauctionBet;

sub object_class { 'BOM::Database::AutoGenerated::Rose::CoinauctionBet' }

__PACKAGE__->make_manager_methods('coinauction_bet');

1;

