package BOM::Database::AutoGenerated::Rose::DailyAggregate::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::DailyAggregate;

sub object_class { 'BOM::Database::AutoGenerated::Rose::DailyAggregate' }

__PACKAGE__->make_manager_methods('daily_aggregates');

1;

