package BOM::Database::AutoGenerated::Rose::First::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::First;

sub object_class { 'BOM::Database::AutoGenerated::Rose::First' }

__PACKAGE__->make_manager_methods('firsts');

1;

