package BOM::Database::DataMapper::Account;

=head1 NAME

BOM::Database::DataMapper::Account

=head1 DESCRIPTION

This is a class that will collect general account queries.

=head1 VERSION

0.1

=cut

use Moose;
use BOM::Database::AutoGenerated::Rose::Account::Manager;
use BOM::Database::Model::Account;
use Format::Util::Numbers qw/roundnear/;
use Date::Utility;
use Try::Tiny;
extends 'BOM::Database::DataMapper::AccountBase';

has '_mapper_model_class' => (
    is       => 'ro',
    isa      => 'Str',
    init_arg => undef,
    default  => 'BOM::Database::Model::Account',
);

=head1 METHODS

=over

=item get_balance

get balance of account

=cut

sub get_balance {
    my $self = shift;

    my $account_record = BOM::Database::AutoGenerated::Rose::Account::Manager->get_account(
        query => [
            client_loginid => $self->client_loginid,
            currency_code  => $self->currency_code
        ],
        db => $self->db,
    );

    return 0 unless @$account_record;
    return sprintf '%.2f', roundnear .01, $account_record->[0]->balance;
}

sub last_modified {
    my $self = shift;

    my $dbh = $self->db->dbh;

    my $sql = q{
        SELECT
            max(EXTRACT ('epoch' from last_modified)::BIGINT) as last_modified
        FROM
            transaction.account
        WHERE
            client_loginid = ?
    };

    my $sth = $dbh->prepare($sql);
    $sth->execute($self->client_loginid);

    my $result;
    if ($result = $sth->fetchrow_hashref) {
        return $result->{'last_modified'};
    }

    return;
}

no Moose;
__PACKAGE__->meta->make_immutable;

=back

=head1 AUTHOR

RMG Company

=head1 COPYRIGHT

(c) 2010 RMG Technology (Malaysia) Sdn Bhd

=cut

1;
