package BOM::Database::AutoGenerated::Rose::Audit::FinancialMarketBet;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table  => 'financial_market_bet',
    schema => 'audit',

    columns => [
        operation => {
            type     => 'varchar',
            length   => 10,
            not_null => 1
        },
        stamp => {
            type     => 'timestamp',
            not_null => 1
        },
        pg_userid => {
            type     => 'text',
            not_null => 1
        },
        client_addr => {type => 'scalar'},
        client_port => {type => 'integer'},
        id          => {
            type     => 'bigint',
            not_null => 1
        },
        purchase_time => {
            type    => 'timestamp',
            default => 'now()'
        },
        account_id => {
            type     => 'bigint',
            not_null => 1
        },
        underlying_symbol => {
            type   => 'varchar',
            length => 50
        },
        payout_price => {type => 'numeric'},
        buy_price    => {
            type     => 'numeric',
            not_null => 1
        },
        sell_price      => {type => 'numeric'},
        start_time      => {type => 'timestamp'},
        expiry_time     => {type => 'timestamp'},
        settlement_time => {type => 'timestamp'},
        expiry_daily    => {
            type     => 'boolean',
            default  => 'false',
            not_null => 1
        },
        is_expired => {
            type    => 'boolean',
            default => 'false'
        },
        is_sold => {
            type    => 'boolean',
            default => 'false'
        },
        bet_class => {
            type     => 'varchar',
            length   => 30,
            not_null => 1
        },
        bet_type => {
            type     => 'varchar',
            length   => 30,
            not_null => 1
        },
        remark => {
            type   => 'varchar',
            length => 800
        },
        short_code => {
            type   => 'varchar',
            length => 255
        },
        sell_time    => {type => 'timestamp'},
        fixed_expiry => {type => 'boolean'},
        tick_count   => {type => 'integer'},
    ],

    primary_key_columns => ['id'],

    allow_inline_column_values => 1,
);

1;

