package BOM::Database::AutoGenerated::Rose::Audit::FreeGift::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Audit::FreeGift;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Audit::FreeGift' }

__PACKAGE__->make_manager_methods('free_gift');

1;

