package BOM::Database::AutoGenerated::Rose::Doughflow::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Doughflow;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Doughflow' }

__PACKAGE__->make_manager_methods('doughflow');

1;

