package BOM::Database::AutoGenerated::Rose::MyaffiliatesCommission::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::MyaffiliatesCommission;

sub object_class { 'BOM::Database::AutoGenerated::Rose::MyaffiliatesCommission' }

__PACKAGE__->make_manager_methods('myaffiliates_commission');

1;

