package BOM::Database::AutoGenerated::Rose::QuantsBetVariable::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::QuantsBetVariable;

sub object_class { 'BOM::Database::AutoGenerated::Rose::QuantsBetVariable' }

__PACKAGE__->make_manager_methods('quants_bet_variables');

1;

