package BOM::Database::AutoGenerated::Rose::Audit::ClientAuthenticationMethod::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Audit::ClientAuthenticationMethod;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Audit::ClientAuthenticationMethod' }

__PACKAGE__->make_manager_methods('client_authentication_method');

1;

