package BOM::Database::AutoGenerated::Rose::EndOfDayOpenPosition::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::EndOfDayOpenPosition;

sub object_class { 'BOM::Database::AutoGenerated::Rose::EndOfDayOpenPosition' }

__PACKAGE__->make_manager_methods('end_of_day_open_positions');

1;

