package BOM::Database::AutoGenerated::Rose::Users::LastLogin::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Users::LastLogin;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Users::LastLogin' }

__PACKAGE__->make_manager_methods('last_login');

1;

