package BOM::Database::AutoGenerated::Rose::Epg::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Epg;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Epg' }

__PACKAGE__->make_manager_methods('epg');

1;

