use strict;
use warnings;

use Test::More (tests => 4);
use Test::Warnings;
use BOM::Test::Data::Utility::UnitTestCollectorDatabase qw(:init);
use BOM::Test::Data::Utility::UnitTestDatabase qw(:init);
use BOM::MyAffiliates::ActivityReporter;

my $client = BOM::Test::Data::Utility::UnitTestDatabase::create_client({
    broker_code        => 'CR',
    myaffiliates_token => 'dummy_affiliate_token',
});
my $account = $client->set_default_account('USD');

my $day_one = '2011-03-08 12:59:59';
my $day_two = '2011-03-09 12:59:59';

$client->payment_legacy_payment(
    currency         => 'USD',
    amount           => 9098,
    remark           => 'here is money',
    payment_type     => 'credit_debit_card',
    transaction_time => $day_one,
    payment_time     => $day_one,
);

$client->payment_legacy_payment(
    currency         => 'USD',
    amount           => -987,
    remark           => 'here is money',
    payment_type     => 'credit_debit_card',
    transaction_time => $day_one,
    payment_time     => $day_one,
);

$client->payment_legacy_payment(
    currency         => 'USD',
    amount           => 270,
    remark           => 'here is money',
    payment_type     => 'credit_debit_card',
    transaction_time => $day_two,
    payment_time     => $day_two,
);

my $fmb = BOM::Test::Data::Utility::UnitTestDatabase::create_fmb({
    type             => 'fmb_higher_lower',
    account_id       => $account->id,
    buy_price        => 456,
    sell_price       => 40,
    payment_time     => $day_one,
    transaction_time => $day_one,
    start_time       => $day_one,
    expiry_time      => $day_one,
});

my $account_data = {
    client_loginid => $client->loginid,
    currency_code  => 'USD',
};
my $fmb_helper = BOM::Database::Helper::FinancialMarketBet->new({
    account_data => $account_data,
    bet          => $fmb,
    db           => $account->db,
});
$fmb_helper->bet_data->{quantity}  = 1;
$fmb_helper->bet_data->{sell_time} = Date::Utility->new($day_one)->plus_time_interval('15s')->db_timestamp;
$fmb_helper->buy_bet;

my $trxn = BOM::Database::AutoGenerated::Rose::Transaction::Manager->get_transaction(
    query => [
        financial_market_bet_id => $fmb->id,
        action_type             => 'buy'
    ],
    db => $account->db,
)->[0];

$fmb->sell_price(40);
$fmb_helper->sell_bet;

$fmb = BOM::Test::Data::Utility::UnitTestDatabase::create_fmb({
    type             => 'fmb_higher_lower',
    account_id       => $account->id,
    buy_price        => 789,
    sell_price       => 40,
    payment_time     => $day_one,
    transaction_time => $day_one,
    start_time       => $day_one,
    expiry_time      => $day_two,
});

$fmb_helper = BOM::Database::Helper::FinancialMarketBet->new({
    account_data => $account_data,
    bet          => $fmb,
    db           => $account->db,
});
$fmb_helper->bet_data->{quantity}  = 1;
$fmb_helper->bet_data->{sell_time} = Date::Utility->new($day_one)->plus_time_interval('15s')->db_timestamp;
$fmb_helper->buy_bet;

$trxn = BOM::Database::AutoGenerated::Rose::Transaction::Manager->get_transaction(
    query => [
        financial_market_bet_id => $fmb->id,
        action_type             => 'buy'
    ],
    db => $account->db,
)->[0];

$fmb->sell_price(40);
$fmb_helper->sell_bet;

subtest 'Activity report for specific date' => sub {
    plan tests => 2;

    my $reporter = BOM::MyAffiliates::ActivityReporter->new;

    my @csv = $reporter->activity_for_date_as_csv(substr($day_one, 0, 10));
    @csv = grep { my $id = $client->loginid; /$id/ } @csv;    # Filters other clients out

    is(@csv, 1, 'Check if there is only one entry for our client on the report');
    chomp $csv[0];
    diag
        "Date, Client Loginid, company profit/loss from client, deposits, turnover_runbets, intraday turnover, other turnover, first funded date, withdrawals, first funded amount";
    is(
        $csv[0],
        '2011-03-08,' . $client->loginid . ',1165.00,9098.00,0.00,912.00,1578.00,2011-03-08,987.00,9098.00',
        'Check if values are correct in report'
    );
};

subtest 'Not funded account with transaction (bonus?)' => sub {
    plan tests => 1;

    my $client = BOM::Test::Data::Utility::UnitTestDatabase::create_client({
        broker_code        => 'CR',
        myaffiliates_token => 'dummy_affiliate_token',
    });
    my $account = $client->set_default_account('USD');

    $client->payment_legacy_payment(
        currency     => 'USD',
        amount       => 5000,
        remark       => 'here is money',
        payment_type => 'credit_debit_card',
    );

    $client->payment_legacy_payment(
        currency     => 'USD',
        amount       => 800,
        remark       => 'here is money',
        payment_type => 'credit_debit_card',
    );

    BOM::Test::Data::Utility::UnitTestDatabase::create_fmb({
        type             => 'fmb_higher_lower',
        account_id       => $account->id,
        buy_price        => 789,
        sell_price       => 40,
        payment_time     => $day_one,
        transaction_time => $day_one,
        start_time       => $day_one,
        expiry_time      => $day_two,
    });

    my @csv = BOM::MyAffiliates::ActivityReporter->new->activity_for_date_as_csv(substr($day_one, 0, 10));
    @csv = grep { my $id = $client->loginid; /$id/ } @csv;
    is(@csv, 1, 'Client is on the list');
};

subtest 'Virtual clients are not reported' => sub {
    plan tests => 1;

    my $client = BOM::Test::Data::Utility::UnitTestDatabase::create_client({
        broker_code        => 'VRTC',
        myaffiliates_token => 'dummy_affiliate_token',
    });
    my $account = $client->set_default_account('USD');

    $client->payment_legacy_payment(
        currency         => 'USD',
        amount           => 270,
        remark           => 'here is money',
        payment_type     => 'credit_debit_card',
        transaction_time => $day_two,
        payment_time     => $day_two,
    );

    my @csv = BOM::MyAffiliates::ActivityReporter->new->activity_for_date_as_csv(substr($day_one, 0, 10));
    @csv = grep { /VRTC/ } @csv;    # Filters only VRTC clients
    is(@csv, 0, 'No Virtual client is not on the list');
};
