package BOM::RiskReporting::Client;

=head1 NAME

BOM::RiskReporting::Client

=head1 DESCRIPTION

Generates a client risk report

=cut

use strict;
use warnings;
use Moose;
extends 'BOM::RiskReporting::Base';

use Excel::Writer::XLSX;
use File::Temp qw(tmpnam);

has client => (
    is => 'rw',
);

has workbook => (
    is => 'rw',
    lazy_build => 1,
);

sub _build_workbook {
    my $self = shift;
    return Excel::Writer::XLSX->new($self->_workbook_file);
}

has _workbook_file => (
    is => 'rw',
    default => sub {return tmpnam()}
);


sub _client_details {
    my $self = shift;

    my $worksheet = $self->workbook->add_worksheet('client details');

    my $count = 0;
    for my $key (BOM::Database::AutoGenerated::Rose::Client->meta->column_names) {
        next if $key =~ /(client_password|secret_answer)/;
        $count++;
        $worksheet->write( "A$count", $key );
        $worksheet->write( "B$count", $self->client->$key );
    }


    return;
}

sub generate {
    my $self = shift;
    my $loginid = shift;

    $self->db_broker_code($self->client->broker);

    $self->_client_details;
    # $self->_total_deposits_withdrawals;
    # $self->_documents_on_file;
    # $self->_financial_assessment_results;
    # $self->_change_of_IP;
    # $self->_change_of_status;
    # $self->_review_of_trades_bets;
    # $self->_comments;

    print $self->_workbook_file;
}

no Moose;
__PACKAGE__->meta->make_immutable;
1;
