package BOM::Database::AutoGenerated::Rose::OpenContractAggregate::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::OpenContractAggregate;

sub object_class { 'BOM::Database::AutoGenerated::Rose::OpenContractAggregate' }

__PACKAGE__->make_manager_methods('open_contract_aggregates');

1;

