package BOM::Database::AutoGenerated::Rose::Users::FailedLogin::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::Users::FailedLogin;

sub object_class { 'BOM::Database::AutoGenerated::Rose::Users::FailedLogin' }

__PACKAGE__->make_manager_methods('failed_login');

1;

