package BOM::Database::AutoGenerated::Rose::Auth::AuthCode;

use strict;

use base qw(BOM::Database::Rose::DB::Object::AutoBase1);

__PACKAGE__->meta->setup(
    table   => 'auth_codes',
    schema   => 'auth',

    columns => [
        auth_code => { type => 'varchar', length => 16, not_null => 1 },
        expires   => { type => 'timestamp', not_null => 1 },
        grant_id  => { type => 'integer', not_null => 1 },
        used      => { type => 'boolean', default => 'false' },
    ],

    primary_key_columns => [ 'auth_code' ],

    foreign_keys => [
        grant => {
            class       => 'BOM::Database::AutoGenerated::Rose::Auth::Grant',
            key_columns => { grant_id => 'id' },
        },
    ],
);

1;

