package BOM::Database::AutoGenerated::Rose::LookbackOption::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use BOM::Database::AutoGenerated::Rose::LookbackOption;

sub object_class { 'BOM::Database::AutoGenerated::Rose::LookbackOption' }

__PACKAGE__->make_manager_methods('lookback_option');

1;

